version: '3'
services:
  node:
    build: 
      context: ./node
    container_name: node
    image: lucasferraz2000/nodejs-fullcycle
    hostname: node
    networks:
      - nodenet
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    image: lucasferraz2000/nginx-fullcycle
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - nodenet
networks:
 nodenet:
  name: nodenet
  driver: bridge
       
