version: '3'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    image: lucasferraz2000/nodejs-fullcycle
    hostname: node
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    command: bash -c "npm install express --save && node index.js"
    tty: true

  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: lucasferraz2000/nginx-fullcycle
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - nodenet
networks:
 nodenet:
  driver: bridge
       
